version: "3"
services:

  sender:
    image: alpine/httpie
    links:
      - voyeur:receiver

  receiver:
    image: kennethreitz/httpbin
    ports: ["8888:80"]
    expose: ["80"]
    command: ["gunicorn", "-b", "0.0.0.0:80", "httpbin:app"]

  voyeur:
    image: voyeur:latest
    build: .
    restart: always
    ports:
      - "9999:80"
    links:
      - receiver
