client:
  cmds:
    - go run ./src/client.go

server:
  cmds:
    - go run ./src/server.go

proxy:
  cmds:
    - go run ./src/proxy.go

build:
  cmds:
    - go build -v -i ./src/proxy.go
    - go build -v -i ./src/client.go